import { BasePresetSizeTypes, Sizes } from '../types/sizes';
import { Typography } from '../types/typography';
declare enum SizePrefix {
    title = "title",
    heading = "heading",
    text = "text",
    label = "label",
    space = "space"
}
export type SizeValuesType = Partial<Sizes> | Partial<Typography>;
export interface GenerateThemeValuesProps {
    scale: BasePresetSizeTypes;
    values: SizeValuesType;
}
/**
 * Generate values for a theme based on base values and scale ratio
 * @param valuesData - The data to generate the values
 * @returns The generated values
 * @example
 * const values = generateThemeValues({
 * scale: 'sm',
 * values: {
 *  title1: 16,
 *  title2: 24,
 *  title3: 36,
 * },
 * });
 * console.log(values);
 * // {
 * //   title1: 14,
 * //   title2: 22,
 * //   title3: 32,
 * // }
 * @remarks
 * This method generates values for a theme based on base values and scale ratio. The values are generated by multiplying the base value by the scale ratio.
 */
export declare const generateThemeValues: (valuesData: GenerateThemeValuesProps) => SizeValuesType;
export interface GenerateThemeSizeScaleProps {
    prefix: keyof typeof SizePrefix;
    base: number;
    ratio: number;
    shift: number;
    count?: number;
    postFix?: number;
}
/**
 * Generate a scale of sizes based on a base value, ratio, and shift
 * @param scaleData - The data to generate the scale
 * @returns The generated scale
 * @example
 * const scale = generateThemeSizeScale({
 *  prefix: 'title',
 * base: 16,
 * ratio: 1.5,
 * shift: 0.5,
 * count: 10,
 * postFix: 1,
 * });
 * // scale = {
 * //   title1: 16,
 * //   title2: 24,
 * //   title3: 36,
 * //   title4: 54,
 * //   title5: 81,
 * //   title6: 121,
 * //   title7: 181,
 *  //  title8: 271,
 * //   title9: 406,
 * //   title10: 609,
 * // }
 * @remarks
 * This method generates a scale of sizes based on a base value, ratio, and shift. The scale is generated by multiplying the base value by the ratio plus the shift for each step in the scale.
 */
export declare const generateThemeSizeScale: (scaleData: GenerateThemeSizeScaleProps) => SizeValuesType;
export {};
